In [36]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [37]:
df = pd.read_csv(r'C:\Users\kinnari\Desktop\Data_Analysis\Python\Telco_Customer_Churn.csv')
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [38]:
#Droping the duplicates if any

df = df.drop_duplicates()
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

It is observed that there were no duplicates in the dataset which is the first milestone in data cleaning.

In [39]:
df1 = df.drop(columns=['SeniorCitizen','Partner'])

In [40]:
#columns_replaced = ["Dependents","PhoneService","MultipleLines","OnlineSecurity","OnlineBackup","DeviceProtection","TechSupport","StreamingTV","StreamingMovies","PaperlessBilling","Churn"]

#df[columns_replaced] = df[columns_replaced].str.replace('Yes', 'Y')
#df[columns_replaced] = df[columns_replaced].str.replace('No','N')

df2 = df1.replace(['Yes', 'No'], ['Y', 'N'])

In [41]:
df2

,customerID,gender,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,N,1,N,No phone service,DSL,N,Y,N,N,N,N,Month-to-month,Y,Electronic check,29.85,29.85,N
1,5575-GNVDE,Male,N,34,Y,N,DSL,Y,N,Y,N,N,N,One year,N,Mailed check,56.95,1889.5,N
2,3668-QPYBK,Male,N,2,Y,N,DSL,Y,Y,N,N,N,N,Month-to-month,Y,Mailed check,53.85,108.15,Y
3,7795-CFOCW,Male,N,45,N,No phone service,DSL,Y,N,Y,Y,N,N,One year,N,Bank transfer (automatic),42.30,1840.75,N
4,9237-HQITU,Female,N,2,Y,N,Fiber optic,N,N,N,N,N,N,Month-to-month,Y,Electronic check,70.70,151.65,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,Y,24,Y,Y,DSL,Y,N,Y,Y,Y,Y,One year,Y,Mailed check,84.80,1990.5,N
7039,2234-XADUH,Female,Y,72,Y,Y,Fiber optic,N,Y,Y,N,Y,Y,One year,Y,Credit card (automatic),103.20,7362.9,N
7040,4801-JZAZL,Female,Y,11,N,No phone service,DSL,Y,N,N,N,N,N,Month-to-month,Y,Electronic check,29.60,346.45,N
7041,8361-LTMKD,Male,N,4,Y,Y,Fiber optic,N,N,N,N,N,N,Month-to-month,Y,Mailed check,74.40,306.6,Y
7042,3186-AJIEK,Male,N,66,Y,N,Fiber optic,Y,N,Y,Y,Y,Y,Two year,Y,Bank transfer (automatic),105.65,6844.5,N

In [42]:
df2.groupby('PaymentMethod').mean(numeric_only=True)

                              tenure  MonthlyCharges
PaymentMethod
Bank transfer (automatic)  43.656736       67.192649
Credit card (automatic)    43.269382       66.512385
Electronic check           25.174630       76.255814
Mailed check               21.830025       43.917060

In [47]:
df2[df2['gender'].str.contains('Female')]

,customerID,gender,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,N,1,N,No phone service,DSL,N,Y,N,N,N,N,Month-to-month,Y,Electronic check,29.85,29.85,N
4,9237-HQITU,Female,N,2,Y,N,Fiber optic,N,N,N,N,N,N,Month-to-month,Y,Electronic check,70.70,151.65,Y
5,9305-CDSKC,Female,N,8,Y,Y,Fiber optic,N,N,Y,N,Y,Y,Month-to-month,Y,Electronic check,99.65,820.5,Y
7,6713-OKOMC,Female,N,10,N,No phone service,DSL,Y,N,N,N,N,N,Month-to-month,N,Mailed check,29.75,301.9,N
8,7892-POOKP,Female,N,28,Y,Y,Fiber optic,N,N,Y,Y,Y,Y,Month-to-month,Y,Electronic check,104.80,3046.05,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7034,0639-TSIQW,Female,N,67,Y,Y,Fiber optic,Y,Y,Y,N,Y,N,Month-to-month,Y,Credit card (automatic),102.95,6886.25,Y
7036,7750-EYXWZ,Female,N,12,N,No phone service,DSL,N,Y,Y,Y,Y,Y,One year,N,Electronic check,60.65,743.3,N
7037,2569-WGERO,Female,N,72,Y,N,N,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Y,Bank transfer (automatic),21.15,1419.4,N
7039,2234-XADUH,Female,Y,72,Y,Y,Fiber optic,N,Y,Y,N,Y,Y,One year,Y,Credit card (automatic),103.20,7362.9,N
7040,4801-JZAZL,Female,Y,11,N,No phone service,DSL,Y,N,N,N,N,N,Month-to-month,Y,Electronic check,29.60,346.45,N

In [48]:
df2[df2['gender'].str.contains('Male')]

,customerID,gender,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
1,5575-GNVDE,Male,N,34,Y,N,DSL,Y,N,Y,N,N,N,One year,N,Mailed check,56.95,1889.5,N
2,3668-QPYBK,Male,N,2,Y,N,DSL,Y,Y,N,N,N,N,Month-to-month,Y,Mailed check,53.85,108.15,Y
3,7795-CFOCW,Male,N,45,N,No phone service,DSL,Y,N,Y,Y,N,N,One year,N,Bank transfer (automatic),42.30,1840.75,N
6,1452-KIOVK,Male,Y,22,Y,Y,Fiber optic,N,Y,N,N,Y,N,Month-to-month,Y,Credit card (automatic),89.10,1949.4,N
9,6388-TABGU,Male,Y,62,Y,N,DSL,Y,Y,N,N,N,N,One year,N,Bank transfer (automatic),56.15,3487.95,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7033,9767-FFLEM,Male,N,38,Y,N,Fiber optic,N,N,N,N,N,N,Month-to-month,Y,Credit card (automatic),69.50,2625.25,N
7035,8456-QDAVC,Male,N,19,Y,N,Fiber optic,N,N,N,N,Y,N,Month-to-month,Y,Bank transfer (automatic),78.70,1495.1,N
7038,6840-RESVB,Male,Y,24,Y,Y,DSL,Y,N,Y,Y,Y,Y,One year,Y,Mailed check,84.80,1990.5,N
7041,8361-LTMKD,Male,N,4,Y,Y,Fiber optic,N,N,N,N,N,N,Month-to-month,Y,Mailed check,74.40,306.6,Y
7042,3186-AJIEK,Male,N,66,Y,N,Fiber optic,Y,N,Y,Y,Y,Y,Two year,Y,Bank transfer (automatic),105.65,6844.5,N

In [54]:
df2.sort_values(by='tenure').head(20)

,customerID,gender,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
1340,1371-DWPAZ,Female,Y,0,N,No phone service,DSL,Y,Y,Y,Y,Y,N,Two year,N,Credit card (automatic),56.05,,N
936,5709-LVOEQ,Female,Y,0,Y,N,DSL,Y,Y,Y,N,Y,Y,Two year,N,Mailed check,80.85,,N
6670,4075-WKNIU,Female,Y,0,Y,Y,DSL,N,Y,Y,Y,Y,N,Two year,N,Mailed check,73.35,,N
4380,2520-SGTTA,Female,Y,0,Y,N,N,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,N,Mailed check,20.00,,N
5218,2923-ARZLG,Male,Y,0,Y,N,N,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Y,Mailed check,19.70,,N
3826,3213-VVOLG,Male,Y,0,Y,Y,N,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,N,Mailed check,25.35,,N
753,3115-CZMZD,Male,Y,0,Y,N,N,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,N,Mailed check,20.25,,N
6754,2775-SEFEE,Male,Y,0,Y,Y,DSL,Y,Y,N,Y,N,N,Two year,Y,Bank transfer (automatic),61.90,,N
3331,7644-OMVMY,Male,Y,0,Y,N,N,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,N,Mailed check,19.85,,N
488,4472-LVYGI,Female,Y,0,N,No phone service,DSL,Y,N,Y,Y,Y,N,Two year,Y,Bank transfer (automatic),52.55,,N
1082,4367-NUYAO,Male,Y,0,Y,Y,N,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,N,Mailed check,25.75,,N
4275,2692-PFYTJ,Female,N,1,Y,Y,N,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Y,Mailed check,25.75,25.75,N
6623,9248-OJYKK,Male,N,1,Y,Y,Fiber optic,N,N,N,N,N,N,Month-to-month,Y,Electronic check,76.45,76.45,Y
6620,6457-USBER,Male,N,1,Y,N,Fiber optic,N,N,N,N,N,Y,Month-to-month,Y,Electronic check,80.80,80.8,Y
1373,4291-HPAXL,Male,Y,1,Y,N,N,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,N,Mailed check,19.85,19.85,N
1371,6567-HOOPW,Female,N,1,Y,N,Fiber optic,N,N,N,N,Y,N,Month-to-month,Y,Electronic check,79.20,79.2,Y
4290,7734-DBOAI,Female,Y,1,N,No phone service,DSL,N,N,N,Y,Y,N,Month-to-month,N,Electronic check,40.10,40.1,Y
5724,8042-JVNFH,Male,N,1,Y,N,Fiber optic,N,N,N,N,N,N,Month-to-month,Y,Mailed check,71.35,71.35,Y
1383,3334-CTHOL,Female,N,1,Y,Y,DSL,N,N,N,N,N,N,Month-to-month,Y,Bank transfer (automatic),49.95,49.95,Y
0,7590-VHVEG,Female,N,1,N,No phone service,DSL,N,Y,N,N,N,N,Month-to-month,Y,Electronic check,29.85,29.85,N

In [55]:
df2.dtypes

customerID           object
gender               object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [63]:
df.nunique()

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [76]:
df2.select_dtypes(include='object')

,customerID,gender,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn
0,7590-VHVEG,Female,N,N,No phone service,DSL,N,Y,N,N,N,N,Month-to-month,Y,Electronic check,29.85,N
1,5575-GNVDE,Male,N,Y,N,DSL,Y,N,Y,N,N,N,One year,N,Mailed check,1889.5,N
2,3668-QPYBK,Male,N,Y,N,DSL,Y,Y,N,N,N,N,Month-to-month,Y,Mailed check,108.15,Y
3,7795-CFOCW,Male,N,N,No phone service,DSL,Y,N,Y,Y,N,N,One year,N,Bank transfer (automatic),1840.75,N
4,9237-HQITU,Female,N,Y,N,Fiber optic,N,N,N,N,N,N,Month-to-month,Y,Electronic check,151.65,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,Y,Y,Y,DSL,Y,N,Y,Y,Y,Y,One year,Y,Mailed check,1990.5,N
7039,2234-XADUH,Female,Y,Y,Y,Fiber optic,N,Y,Y,N,Y,Y,One year,Y,Credit card (automatic),7362.9,N
7040,4801-JZAZL,Female,Y,N,No phone service,DSL,Y,N,N,N,N,N,Month-to-month,Y,Electronic check,346.45,N
7041,8361-LTMKD,Male,N,Y,Y,Fiber optic,N,N,N,N,N,N,Month-to-month,Y,Mailed check,306.6,Y
7042,3186-AJIEK,Male,N,Y,N,Fiber optic,Y,N,Y,Y,Y,Y,Two year,Y,Bank transfer (automatic),6844.5,N

In [79]:
#changing object to float - "TotalCharges"

df2['TotalCharges'] = pd.to_numeric(df2['TotalCharges'], errors='coerce')

In [80]:
df2.dtypes

customerID           object
gender               object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [93]:
df2.describe()

       tenure  MonthlyCharges  TotalCharges
count 7043.00         7043.00       7032.00
mean    32.37           64.76       2283.30
std     24.56           30.09       2266.77
min      0.00           18.25         18.80
25%      9.00           35.50        401.45
50%     29.00           70.35       1397.47
75%     55.00           89.85       3794.74
max     72.00          118.75       8684.80